### ISSUE TITLE
error when run kmaToPeptideSeqs.py

### ISSUE THREAD

**Issue by huangxiaogua** [vanallenlab/retained-intron-neoantigen-pipeline#4]
hello,
when I run kmaToPeptideSeqs.py , I met the error messages as follwings:

jm@jm:~/Downloads/retained-intron-neoantigen-pipeline-master$ python kmaToPeptideSeqs.py kma_output_file_example.csv 9 /home/jm/Downloads/retained-intron-neoantigen-pipeline-master/out

Traceback (most recent call last):
  File "kmaToPeptideSeqs.py", line 216, in <module>
    main()
  File "kmaToPeptideSeqs.py", line 213, in main
    getSeqs(uniqueIntrons, TPMvals, window, outpath)
  File "kmaToPeptideSeqs.py", line 173, in getSeqs
    loc,'/home/jm/referance_data/hg19/hg19.2bit','stdout']))
  File "/home/jm/miniconda2/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/home/jm/miniconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/jm/miniconda2/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Can help me to find where is wrong, thank you!

**Comment by huangxiaogua** [comment]
Finally , I have found my path to the twoBitToFa  was wrong.
